/**:
    ros__parameters:
      wheel_radius: 0.033
      track_width: 0.160
      motor_cmd_max: 265
      motor_cmd_per_rad_sec: 0.024
      encoder_ticks_per_rad: 651.81
      collision_radius: 0.11
      input_noise: 0.05
      slip_fraction: 0.01
      basic_sensor_variance: 0.01
      max_range: 1.0