/**:
    ros__parameters:
      rate: 200
      x0: -0.6
      y0: 0.8
      theta0: 1.57
      # obstacles/x: [-0.6, 0.7, 0.5]
      # obstacles/y: [-0.8, -0.7, 0.9]
      # obstacles/r: 0.038
      obstacles:
        x: [-0.6, 0.7, 0.5]
        y: [-0.8, -0.7, 0.9]
        r: 0.038